name: Deploy Blazor Client App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Build and deploy
      run: |
        dotnet build MyBlazorClientApp.csproj -c Release
        dotnet publish MyBlazorClientApp.csproj -c Release -o myapp-publish
        cd myapp-publish
        git init
        git config user.name ${{ secrets.USER_NAME }}
        git config user.email ${{ secrets.USER_EMAIL }}
        git add .
        git commit -m "Deploy to GitHub Pages"
        git push --force "https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git" master:gh-pages
